---
title: "XR251_UMAPs"
author: "Alexander Lercher"
date: "`r Sys.Date()`"
output: github_document
---

## LOAD PACKES
```{r load packages}
library(Seurat)
library(tidyverse)
library(patchwork)
library(cowplot)
library(ggplot2)
library(ggpubr)
library(knitr)
```

## LOAD in SEURAT RDS files from Maria Sierra
```{r load in seurat rds files from Maria Sierra}
data <- readRDS(file = "input/seu_obj_v12192025.RDS")

# rename and plot by sample
table(data@meta.data$orig.ident)
data$condition <-  dplyr::recode(
  data$orig.ident,
  "24177-05-01" = "00_hours",
  "24177-05-02" = "02_hours",
  "24177-05-03" = "16_hours"
)

# rename and plot by sample
table(data@meta.data$manual)
data$manual <- dplyr::case_when(
  data$manual == "VSMCs" ~ "Fibroblast",
  data$manual == "Fibroblast" ~ "Fibroblast-like",
  data$manual == "Ventricular Ephithelial cells" ~ "Ventricular Epithelial cells",
  TRUE ~ as.character(data$manual)              # keep everything else
) %>%
  factor() %>%                                  # convert back to factor
  droplevels()

# rename manual to cell_type (maria called it manual because we annotated manually)
data@meta.data <- data@meta.data %>%
  dplyr::rename(cell_type = manual)

# reset Idents()
Idents(data) <- data$cell_type

#save my modified Seurat object
saveRDS(data, file = "input/seu_obj_v12192025_AL.rds")
```

## INSPECT AND SAVE UMAPs GENERATED BY MARIA
```{r inspect and save UMAPs generated by Maria}
# define colors
cols <- c(
  "#E69F00","#56B4E9","#009E73","#F0E000",
  "#0072B2","#D55E00","#CC79A7","#999999",
  "#1B9E77","#D90F02","#7570B3","#E7298A"
)

# UMAP by cell type
p1 <- DimPlot(data,
              reduction = "umap",
              group.by = "cell_type",
              label = TRUE,
              repel = TRUE,
              cols = cols) +
  theme(aspect.ratio = 1) +
  labs(title = "cell types")

print(p1)
ggsave("output/UMAPs/umap_cell_types.pdf", p1, width = 12, height = 12)

# UMAP split by condition
p2 <- DimPlot(data,
              reduction = "umap",
              split.by = "condition",
              ncol = 3,
              label = TRUE,
              repel = TRUE,
              cols = cols) +
  theme(aspect.ratio = 1) +
  labs(title = "samples")

print(p2)
```

## APPENDIX
```{r appendix}
# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

